KhronosGroup/GLSL

- extensions/ext/GL_EXT_control_flow_attributes.txt
This extension is open for discussion, which can be held here in this pull request.
Basically, it adds control-flow hints (very strong suggestions).  E.g.,
```
[[unroll]]               for (int x = 0; i < 8; ++i) { ... }
[[dont_unroll]]          while(...) { ... }
[[dependency_infinite]]  do { ... } while(...);
[[dependency_length(4)]] for (int x = 0; i < 8; ++i) { ... }
[[flatten]]              if (...) { ... } else { ... }
[[dont_flatten]]         switch(...) { ... }
```
See content of the extension for more detail. There is an implementation under way for this in glslang.
> Add new extension GL_EXT_control_flow_attributes.

- extensions/khr/GL_KHR_shader_subgroup.txt
This commit adds the new GL_KHR_shader_subgroup extension, which adds a rich collection of subgroup functionality to GLSL.
This extension has corresponding new opcodes in SPIR-V 1.3, and is usable in Vulkan 1.1.
> Add the new GL_KHR_shader_subgroup extension.

- extensions/khr/GL_KHR_vulkan_glsl.txt
Shadow sampling does not strictly require a *samplerShadow*.
Addresses Khronos internal issue https://gitlab.khronos.org/spirv/SPIR-V/issues/160.
> Relax rules for *sampler* to allow shadows.

- extensions/ext/GL_EXT_subgroupuniform_qualifier.txt
Add a new GL_EXT_dynamically_uniform_attribute extension that introduces
a variable declaration, function parameter, and function return type
attribute [[dynamically_uniform]] to signify that the value is uniform
across the shader.
This maps to the SPIR-V `Uniform` decoration.
> Add a new GL_EXT_subgroupuniform_qualifier.

- extensions/nv/GLSL_NV_mesh_shader.txt
Update the edits to the huge layout qualifier table in section 4.4 to
clarify that "local_size_[xyz]" is allowed in task shaders.  Other
spec language clearly supports this usage, but the table update was
wrong.
> Fix NV_mesh_shader table to allow "local_size_[xyz]" in task shaders.

- extensions/nv/GLSL_NV_mesh_shader.txt
Add an interaction specifying that the "local_size_[xyz]_in" layout
qualifiers added for compute shaders in GLSL 4.60 and KHR_vulkan_glsl
(SPIR-V compiles only) also work for mesh and task shaders.
@dgkoch @sparmarNV
Note that I am going to be on vacation starting a couple hours from now.  Hopefully Daniel or Sahil can address any feedback issues.
> Allow "local_size_[xyz]_in" in mesh/task shaders where applicable.

- extensions/ext/GL_EXT_shader_atomic_int64.txt
Adding GLSL spec for GL_EXT_shader_atomic_int64
Issue https://github.com/KhronosGroup/Vulkan-Docs/issues/796
> Adding GL_EXT_shader_atomic_int64 Spec

- extensions/khr/GL_KHR_shader_subgroup.txt
The restriction on the mask parameter was never correctly reflected as a
restriction on SPIR-V and is not enforced by any current implementation.
> Remove restriction on ShuffleXor mask parameter

- extensions/ext/GLSL_EXT_buffer_reference.txt
This error was already implemented in glslang, but was missing from the spec.
> Disallow the .length() method on the unsized array member of a buffer reference

- extensions/nv/GLSL_NV_mesh_shader.txt
EXT_clip_cull_distance is not in ES 3.2 so if it's not supported any
interactions with it are removed.
> Add EXT_clip_cull_distance interactions to NV_mesh_shader

- README.md
- extensions/ext/GLSL_EXT_buffer_reference2.txt
This is a GLSL-only followon to GL_EXT_buffer_reference that makes it easier to work with arrays of structures in memory, originally requested by @pixeljetstream.
I have a glslang implementation pending, I will push it soon.
> Add GL_EXT_buffer_reference2 extension

- README.md
- extensions/ext/GL_EXT_shader_realtime_clock.txt
GLSL functions for use with the SPV_KHR_shader_clock extension.
Adds the following glsl functions:
uvec2    clockRealtime2x32EXT(void);
uint64_t clockRealtimeEXT(void);
> Add GL_EXT_shader_realtime_clock extension.

- extensions/khr/GL_KHR_vulkan_glsl.txt
This is described in the Vulkan spec. as 
> Location aliasing is causing two variables to have the same location number. Component aliasing is assigning the same (or overlapping) component number for two location aliases. Location aliasing is allowed only if it does not cause component aliasing. 
But, contradictory language allowing it was still in the GLSL specification. This commit fixes that.
> Record that vertex-input aliasing was removed for Vulkan.

- extensions/khr/GL_KHR_shader_subgroup.txt
When a primitive only partially covers a quad of fragments, additional
fragment shader invocations are generated to fill it out. According to
other documentation, these are helper invocations. This clarifies that
they are helpers, which suggests how the case where the quad is not
completely composed of covered fragments can be detected.
Resolves issue #77
> Clarify nature of added fragments to quads

- extensions/nv/GLSL_NV_compute_shader_derivatives.txt
In NV_compute_shader_derivatives, we disallow the "quads" derivative
mode if the local workgroup size has an odd width or height and
disallow the "linear" derivative mode if the number of threads in the
local workgroup is not a multiple of four.  However, the spec didn't
consider interactions with ARB_compute_variable_group_size, which
allows applications to compile shaders without a fixed group size.  We
can't throw errors for bad group sizes in this case.
In discussion on a Khronos GitHub issue, we decided to instead
implement this check at run-time and throw INVALID_VALUE if a bad
group size is passed to a dispatch call.
This change updates the NV_compute_shader_derivatives spec to specify
no compile-time check in this case.  Additionally, it updates the spec
to specify that errors in …
> Add spec language for compute derivatives with variable group sizes.

- extensions/nv/GLSL_NV_mesh_shader.txt
@johnkslang This change is a minor typo  fix in the changelog of NV_mesh_shader that I found while looking at something unrelated.
> Fix a minor typo in the NV_mesh_shader changelog.

- extensions/ext/GLSL_EXT_demote_to_helper_invocation.txt
Change dependency with "GL_KHR_vulkan_glsl" from requirement to
interaction.  Expand the GLSL spec dependencies.
The goal is make clear that this extension can also be used in OpenGL.
> Update GLSL_EXT_demote_to_helper_invocation dependencies

- extensions/ext/GLSL_EXT_buffer_reference_uvec2.txt
From the overview:
This extension adds additional constructor support to GL_EXT_buffer_reference to enable conversion of references to and from a **uvec2**. That is, the 64 bits of address from the reference are constructed to and from two 32-bit unsigned integers, represented as a vector of two uints.
The intent is to not require 64-bit integer support to manipulate the 64-bits of address in a reference. E.g., a shader can use uaddCarry() to add an offset to a reference address via **uvec2** objects, or compare an address to 0, using a `uvec2(0)` value.
> Add GLSL_EXT_buffer_reference_uvec2

- extensions/khr/GL_KHR_shader_subgroup.txt
Allow the <id> parameters of subgroupBroadcast and
subgroupQuadBroadcast to be dynamically uniform
> broadcast id can be dynamically uniform

- extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt
Typo correction of 'uint64_t,uint64_t' to 'int64_t,uint64_t' ,as mentioned in PR #94
> Typo correction PR #94

- extensions/nv/GLSL_NV_fragment_shader_barycentric.txt
Using cp1252 adds unnecessary trouble parsing extension specification files with scripts.
Fix for #106
> Avoid using cp1252 encoding

- extensions/ext/GLSL_EXT_ray_tracing.txt
Some noticed when reviewing https://github.com/KhronosGroup/GLSL/pull/125
and some pointed out in https://gitlab.khronos.org/GLSL/GLSL/-/issues/21
- clarify that hitAttributeEXT variables can be ready in intersection
shaders as well, but are undefined values before written.
- gl_LaunchIDEXT and gl_LaunchSizeEXT are accessible in callable shaders
on related description issues
- avoid duplicate binding/set in example code
- fix typo in declaration of gl_ScopeShaderCallEXT
> Fix more typographical and grammatical issues in EXT_ray_tracing

- extensions/ext/GLSL_EXT_ray_query.txt
Vulkan issue 2432
The descriptions of rayQueryGetIntersectionPrimitiveIndexEXT
and rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT
were missing.
> Add missing ray query function descriptions

- README.md
- extensions/ext/GL_EXT_subgroup_uniform_control_flow.txt
* Add extension that adds the `subgroups_uniform_control_flow` attribute to entry
point definitions
> GL_EXT_subgroup_uniform_control_flow

- extensions/khr/GL_KHR_shader_subgroup.txt
Originally there was a "if they are active then they participate" clause in the Vulkan spec which was confusing, so we updated it to the current language here: https://www.khronos.org/registry/vulkan/specs/1.3/html/chap9.html#shaders-helper-invocations
This change brings the GLSL extension in line with the API spec
> Clarify helper behavior to match Vulkan spec

- README.md
- extensions/arm/GLSL_ARM_shader_core_builtins.txt
Change-Id: I33988b29010e274d0e5d906a17f3fed60b952486
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Publish GLSL_arm_shader_core_builtins

- README.md
- extensions/ext/GL_EXT_null_initializer.txt
* Adds a null initializer syntax (empty braces) that can be used to
initialize variables
* Allows shared variables to use null initializers
> GL_EXT_null_initializer

- extensions/ext/GL_EXT_control_flow_attributes2.txt
The GLSL extension "GL_EXT_control_flow_attributes" adds attributes to declare how loops should be lowered by a consumer (e.g., unroll and dont_unroll). But not all attributes available in SPIR-V 1.4 are made visible.
The PR is for an extension that adds the attributes missing in the GLSL extension GL_EXT_control_flow_attributes: they are min_iterations, max_iterations, iteration_multiple, peel_count, and partial_count.
Please note that the support for these attributes has already been available in glslangValidator.
> GL_EXT_control_flow_attributes2

- extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt
This was incorrectly spelled "UInt" rather than "Uint" in the extension spec.
Fixes #215.
> Correct spelling of halfBitsToUint16

- extensions/khr/GL_KHR_vulkan_glsl.txt
These are not used in Vulkan because the API does not distinguish these images as different dimensions, allowing mixing-and-matching with samplers that do and do not use unnormalized coordinates.
This update removes the additional Rect handles that were added but could never be used (texture2DRect, etc), explicitly reserves the tokens that already exist in GLSL (sampler2DRect, etc), and adds a brief explanation of how to get this same functionality in Vulkan.
Fixes Vulkan-Docs issue #1582.
> Update GL_KHR_vulkan_glsl for Rect textures

- extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt
> Fix a typo in GL_EXT_shader_explicit_arithmetic_types.txt 

- extensions/ext/GLSL_EXT_spirv_intrinsics.txt
- extensions/extension_headers/GL_AMD_shader_explicit_vertex_parameter.glsl
- extensions/extension_headers/GL_AMD_shader_trinary_minmax.glsl
- extensions/extension_headers/GL_ARB_shader_stencil_export.glsl
- extensions/extension_headers/GL_EXT_ray_flags_primitive_culling.glsl
- extensions/extension_headers/GL_EXT_ray_query.glsl
- extensions/extension_headers/GL_EXT_ray_tracing.glsl
- extensions/extension_headers/GL_EXT_shader_realtime_clock.glsl
This extension enables spirv opcodes, types, decorations, and storage classes to be directly encoded into GLSL via new qualifiers.
Example "headers" are included which show how the extension can be used. An initial PR for review against glslang will be available for review shortly, and I'll link that from here.
> Added first draft of GLSL_EXT_spirv_intrinsics

- chapters/builtinfunctions.adoc
There was an extra '_' which was breaking the italic markup.
Fixes internal issue 78. Thanks, @lexaknyazev
> Fix markup for textureGrad 1D

- chapters/grammar.adoc
Both `switch_statement_list` and `conditionopt` permit an empty entry. In one case we used `_nothing_` and the other `_empty`. As well, the ordering of when the entry was reversed, first in one, second in the other.
This CL makes them consistent by using `_empty_` and listing it first in both grammar productions.
> Make `switch_statement_list` and `conditionopt` consistent.

- chapters/builtinfunctions.adoc
This CL updates the `min` and `max` methods to match the GLSL.std.450 SPIR-V definition by adding a note on the behaviour with NaN values.
Fixes #80
> Update `min`, `max` to match SPIR-V extended instruction.

- chapters/builtinfunctions.adoc
GL does support signed normalized textures, so change the format list in the GLSL spec to remove the word "unsigned" that implied the signed variants were not valid.
Fixes internal issue 76. Thanks, @lexaknyazev
> Avoid implying that normalized texture cannot be signed

- chapters/spirvmappings.adoc
- extensions/khr/GL_KHR_vulkan_glsl.txt
Fix the examples used for specialization constants to remove the implicit type conversion which is not permitted.
Fixes #169
> Fixup example to use `ivec3`.

- chapters/grammar.adoc
An identifier list was defined as one or more identifiers preceded by a comma, so an additional rule was needed for a single identifier. Change the identifier_list to be what would normally be expected, a comma-separated list of one or more identifiers, and remove the additional rule.
> Simplify grammar for identifier_list

- chapters/builtinfunctions.adoc
sqrt and inversesqrt were incorrectly shown as having double precision overloads even in the ES version of the spec. These are removed for ESSL but remain for GLSL.
> ESSL: Stop displaying double-precision overloads

- README.adoc
- extensions/ext/GLSL_EXT_integer_dot_product.txt
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
Change-Id: Ifc55b44217819cf5c6998eeb4aedcc8d7597e65d
> Add GLSL_EXT_integer_dot_product

- extensions/ext/GLSL_EXT_buffer_reference.txt
Noticed in https://github.com/KhronosGroup/glslang/issues/3774 that going 
```glsl
layout(buffer_reference, std140, buffer_reference_align = 8) buffer MyStruct;
layout(buffer_reference) buffer MyStruct {  vec4 x;  };
```
the `std140` and `buffer_reference_align` are ignored but it is not obvious and added clarification
> Clarification for GLSL_EXT_buffer_reference forward declaration
