KhronosGroup/GLSL

- extensions/nv/GLSL_NV_compute_shader_derivatives.txt
In NV_compute_shader_derivatives, document interactions with
EXT_sparse_texture2.
> NV_compute_shader_derivatives + EXT_sparse_texture2

- extensions/nv/GLSL_NV_ray_tracing.txt
Add SPIR-V mapping, clarify gl_InstanceID
> Updates for GLSL_NV_ray_tracing

- extensions/ext/GLSL_EXT_buffer_reference.txt
(set WIP just to give time for review)
> Clarify how buffer reference types interact with const and constant expressions, and which operators are supported

- extensions/nv/GLSL_NV_ray_tracing.txt
@jeffbolznv to assist merge
@johnkslang for visibility
> Fix language to allow only read access to shaderRecordNV buffers.

- extensions/ext/GLSL_EXT_buffer_reference.txt
> Fix issue 63: typo in GLSL_EXT_buffer_reference

- extensions/nv/GLSL_NV_ray_tracing.txt
Fixes #93 and #95 
cc @alelenv @ewerness-nv please review.
> Fixes for GLSL_NV_ray_tracing

- extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt
Removing extra white space in tables and aligning tables following PR  #101
> Alignment of tables

- README.md
- extensions/ext/GLSL_EXT_ray_flags_primitive_culling.txt
- extensions/ext/GLSL_EXT_ray_query.txt
- extensions/ext/GLSL_EXT_ray_tracing.txt
Addressees vulkan issue #2073
KhronosGroup/glslang#2169
> Split primitive culling ray flags to separate extension

- extensions/ext/GLSL_EXT_ray_flags_primitive_culling.txt
Spec update for primitive_culling.
@dgkoch for initial review
> Update spec with new layout qualifier.

- README.md
> Update README.md - fix link for vulkan_relaxed

- extensions/ext/GLSL_EXT_ray_query.txt
> Fix minor typo

- extensions/ext/GLSL_EXT_ray_query.txt
> Swap descriptions of rqGIOR Origin/Direction

- extensions/nv/GLSL_NV_ray_tracing.txt
> add subgroup and clock interactions to NV_ray_tracing

- extensions/ext/GLSL_EXT_ray_query.txt
> Clarify SPIR-V mapping for <committed> arg in GLSL_EXT_ray_query

- README.md
- extensions/ext/GLSL_EXT_ray_cull_mask.txt
> Add GL_EXT_ray_cull_mask

- extensions/ext/GLSL_EXT_ray_flags_primitive_culling.txt
- extensions/ext/GLSL_EXT_ray_query.txt
- extensions/ext/GLSL_EXT_ray_tracing.txt
> Disallow more combinations of ray flags

- extensions/ext/GLSL_EXT_ray_query.txt
Fixes https://github.com/KhronosGroup/GLSL/issues/149
> Add note explaining pass-by-pointer for ray query

- README.md
I'll get this right one of these times ;-)
> Remove vestigial .txt from the index

- README.md
- extensions/nv/GLSL_NV_shader_invocation_reorder.txt
> Add spec for GL_NV_shader_invocation_reorder.

- README.md
- extensions/ext/GL_EXT_terminate_invocation.txt
* New GLSL extension to correspond with SPV_KHR_terminate
* Adds terminate jump
> Add GL_EXT_terminate_invocation

- README.md
- extensions/khr/GLSL_KHR_cooperative_matrix.txt
I've imported this as-is from the private repo, so we can do final review here.
> Initial revision of GL_KHR_cooperative_matrix

- README.adoc
- extensions/nv/GLSL_NV_cluster_acceleration_structure.txt
@jeffbolznv to review and merge
> Add GLSL_NV_cluster_acceleration_structure.

- README.adoc
- extensions/nv/GLSL_NV_linear_swept_spheres.txt
@jeffbolznv to review and merge
> Add GLSL_NV_linear_swept_spheres.

- extensions/ext/GL_EXT_shader_realtime_clock.txt
Discussed on issue here: https://github.com/KhronosGroup/GLSL/issues/280
> Add ESSL support for GL_EXT_shader_realtime_clock
